### ISSUE TITLE
Several Yeelight bulbs...

### ISSUE THREAD

**Issue by damison** [jomwells/ambilight-yeelight#9]
Hello, is it possible to integrate several Yeelight bulbs?
In the configuration.yaml file, I can't integrate my second bulb.
an idea ?

**Comment by Torrecilla** [comment]
I have the same issue.
My setup includes a yeelight bulb and a yeelight strip.
Both lamps were working perfectly on the very early versions, but with the upcoming updates this never worked the same again.
Now I can turn on either the bulb or the strip and will match the TV ambilight system, but not both at the same time.

**Comment by lorenc88** [comment]
Experiencing the same issue with 2 yeelight bulbs

**Comment by BenGost** [comment]
I added the two bulbs like this, but it doesn't work.
On the other hand, on the app I can clearly see my two bulbs in "MusicFlow" mode.

```
switch:
  - platform: philips_ambilight+yeelight
    name: Lounge Lamp (Right) # (Name in Front-End)
    host: 192.168.1.166 # (the TV)
    username: XXX
    password: XXX
    address: 192.168.1.185 # (The Bulb)
    display_options: right
  - platform: philips_ambilight+yeelight
    name: Lounge Lamp (LEFT) # (Name in Front-End)
    host: 192.168.1.166 # (the TV)
    username: XXX
    password: XXX
    address: 192.168.1.163 # (The Bulb)
    display_options: right
```

**Comment by arecdudek** [comment]
Still no one have a resolution for this? :(

**Comment by jpcurti** [comment]
I checked the script and it seems pretty feasible to adapt it for multiple lamps, however, I do not have yeelight lamps at home (just a ceiling light that unfortunately does not supports music flow mode). If I create a fork for you guys can someone test it and tell if it works?

Edit: here is a very very simple test. Please note that I have absolutely idea if it works like this with the home assistant configuration file. If this works, I can make a clean implementation that takes a list of bulbs. You can replace the switch.py on the fork for the one that was probably located on ```config/custom_components/ambilight-yeelight``` 
https://github.com/jpcurti/ambilight-yeelight

**Comment by Torrecilla** [comment]
> 
> 
> I checked the script and it seems pretty feasible to adapt it for multiple lamps, however, I do not have yeelight lamps at home (just a ceiling light that unfortunately does not supports music flow mode). If I create a fork for you guys can someone test it and tell if it works?
> 
> Edit: here is a very very simple test. Please note that I have absolutely idea if it works like this with the home assistant configuration file. If this works, I can make a clean implementation that takes a list of bulbs. You can replace the switch.py on the fork for the one that was probably located on `config/custom_components/ambilight-yeelight`
> https://github.com/jpcurti/ambilight-yeelight

Count me in for the test, my setup includes an Ambilight TV, Yeeelight color bulb and Yeelight led strips.

**Comment by lorenc88** [comment]
@jpcurti i installed your fork via HACS and will test it.

**Comment by jpcurti** [comment]
> @jpcurti i installed your fork via HACS and will test it.

Hi please keep in mind that is it a very very simple change and the goal was just to check if such change would work. If both lamps can get the same color flow from the TV then I would spend some time to make it right :) there is no checking if the second lamp is connected and in music mode, for example. It just take both addresses and try to send the color to both lamps at the same time.

Specify on the address field of the configuration both addresses with an ", " (comma and space) between them.

Please let me know if it works and if it don't what happens e.g only the first, only the second or none of them :) and thanks btw for verifying it.

**Comment by jpcurti** [comment]
> @jpcurti i installed your fork via HACS and will test it.

Any news on this?

**Comment by lorenc88** [comment]
> > @jpcurti i installed your fork via HACS and will test it.
> 
> Any news on this?

Sorry for the delay. Wasn't able to run it. I uninstalled the original addon, then installed yours using HACS.
Added the modified configuration:

```
    - platform: philips_ambilight+yeelight
      switches:
        yee_ambi_left:
          name: YeeAmbi lewy # (Name in Front-End)
          host: 192.168.1.253 # (the TV)
          username: XXX
          password: XXX
          address: 192.168.1.146, 192.168.1.145 # (The Bulb)
          display_options: left
```

When I save config and try to validate it before the restart it isn't able to finish it. When i try to restart it throws:
![Screenshot_34](https://user-images.githubusercontent.com/7231335/117619864-131c3000-b170-11eb-9ce3-9dd149e1dba7.png)

All that was changed in comparison to original config is this line:
`address: 192.168.1.146, 192.168.1.145 `
